### ISSUE TITLE
error message using shovel or tunnel

### ISSUE THREAD

**Issue by lambda2501** [michaelskyba/tunnel#3]
When using shovel or tunnel, I got an error message then the program stop.
For example, using `shovel <deck file>` then the first choice `1) Start the review`, it shows the front, then show an error :
```bash
Front ==================================================
深い

Try recalling the back of the card.
Once you've tried your best, press Enter to flip the card.

/usr/local/bin/shovel: 246: read: arg count
```

My current test deck file :
```bash
 深い    ふかい profond⋅e, épais⋅se 深い森
 ```

My system :
```bash
Linux 5.15.39_1 #1 SMP Fri May 13 11:39:37 UTC 2022 VoidLinux GNU/Linux
```

**Comment by michaelskyba** [comment]
Hello lambda2501, thank you for trying the project and posting this issue.

Line 246 of shovel is ``read -r``. I think what's going on is that your shell's ``read`` implementation requires a variable to be provided, which isn't the case here. On my system, your deck file works fine, since my ``read`` _doesn't_ require a variable:
![temp](https://user-images.githubusercontent.com/57649592/172159832-da7d7c88-c9dc-417e-8ffa-c53dd73cb98a.png)

In oksh, which I've been using, it works, but with dash, which I just tried, it doesn't work. To confirm this, try installing the version I made on the standard_read branch:

```sh
cd "<the directory you have tunnel in>"
git pull
git checkout standard_read
su -c "cp shovel /usr/local/bin/"
```

and see if it solves the issue. If it does, I can merge it into the main branch.

**Comment by michaelskyba** [comment]
It seems to work on my machine, and I haven't received any follow-up from lambda, so I'm just going to merge it and close this issue. Feel free to open it back up if, after updating, you're still encountering the problem.

**Comment by michaelskyba** [comment]
(Since it's in the main branch, you can just ``git pull`` from your original installation. The ``default_branch`` has been deleted.)

**Comment by michaelskyba** [comment]
https://github.com/michaelskyba/tunnel/commit/dd4c44347f179dfb45771c728e42d9bd21ff4852
